// src/app/(public)/courses/mockCoursesData.ts
import { type Course } from '@/components/shared/CourseCard';
import { Users, Award, Video, FileText, Brain, ClipboardCheck, Target, MessageSquare, MessageCircle, Clock } from 'lucide-react';

export const coursesData: Course[] = [
  { 
    id: "a1-a2-beginner", 
    title: "A1-A2 Beginner", 
    shortDescription: "Start your French journey. Build a strong foundation from scratch.", 
    targetCLB: "1-4", 
    format: "Group / 1-on-1",
    duration: "12 Weeks",
    imageUrl: "https://placehold.co/600x400.png",
    imageAiHint: "classroom study group",
    price1on1: 399,
    price1on3: 249,
    detailedDescription: "Our A1-A2 Beginner course is meticulously designed for those with little to no French knowledge. We focus on building a strong grammatical base, essential vocabulary, and an introduction to practical conversation. This course prepares you to confidently handle everyday situations in French.",
    whatsIncluded: [
      { text: "Live Interactive Classes", icon: Users },
      { text: "Certified Instructors", icon: Award },
      { text: "Comprehensive Class Notes (PDF)", icon: FileText },
      { text: "Basic Conversation Practice", icon: MessageSquare },
      { text: "Beginner Level Mock Tests", icon: ClipboardCheck },
    ],
  },
  { 
    id: "b1-b2-intermediate", 
    title: "B1-B2 Intermediate", 
    shortDescription: "Enhance your fluency and prepare for the TEF Canada exam.", 
    targetCLB: "5-7", 
    format: "Group / 1-on-1",
    duration: "16 Weeks",
    imageUrl: "https://placehold.co/600x400.png",
    imageAiHint: "professional discussion group",
    price1on1: 399,
    price1on3: 249,
    detailedDescription: "The B1-B2 Intermediate course is engineered for learners aiming for high scores essential for Express Entry. This program dives deep into advanced strategies for each TEF Canada module, with extensive practice, mock tests, and personalized feedback to ensure you are fully prepared to achieve CLB 5-7.",
    whatsIncluded: [
      { text: "Advanced Live Interactive Classes", icon: Users },
      { text: "Expert TEF Instructors (CLB 9+)", icon: Award },
      { text: "All Class Recordings (24/7 Access)", icon: Video },
      { text: "AI Language Tutor Access", icon: Brain },
      { text: "Extensive Official TEF Practice Materials", icon: ClipboardCheck },
      { text: "Multiple Full-Length Mock Tests & In-depth Feedback", icon: Target },
    ],
  },
   { 
    id: "c1-c2-advanced", 
    title: "C1-C2 Advanced", 
    shortDescription: "Perfect your French to a near-native level for professional and academic success.", 
    targetCLB: "8+", 
    format: "1-on-1 Coaching",
    duration: "20 Weeks",
    imageUrl: "https://placehold.co/600x400.png",
    imageAiHint: "expert award ceremony",
    price1on1: 399,
    detailedDescription: "The C1-C2 Advanced course is for advanced French speakers targeting the highest CLB levels to maximize their CRS points or for professional fluency. This highly personalized 1-on-1 coaching focuses on perfecting nuances, advanced vocabulary, and flawless execution.",
     whatsIncluded: [
        { text: "Elite 1:1 Coaching Sessions", icon: Users },
        { text: "Personalized Study Plan", icon: ClipboardCheck },
        { text: "Advanced Material & Error Analysis", icon: Brain },
        { text: "Focus on Idiomatic Expressions", icon: MessageSquare },
        { text: "Dedicated WhatsApp Group", icon: MessageCircle },
    ],
  },
  { 
    id: "tef-canada-prep", 
    title: "TEF Canada Test Prep", 
    shortDescription: "Specialized, intensive preparation to ace the TEF exam.", 
    targetCLB: "7+", 
    format: "Group / 1-on-1",
    duration: "8 Weeks",
    imageUrl: "https://placehold.co/600x400.png",
    imageAiHint: "exam study focus",
    price1on1: 399,
    price1on3: 249,
    detailedDescription: "This is a laser-focused boot camp designed to maximize your TEF Canada score in a short amount of time. We cover all sections of the exam with proven strategies, time-management techniques, and intensive mock test sessions.",
     whatsIncluded: [
        { text: "Intensive Strategy Sessions", icon: Target },
        { text: "Full-Length Mock Exams", icon: ClipboardCheck },
        { text: "Personalized Feedback", icon: Award },
        { text: "Time Management Techniques", icon: Clock },
        { text: "Access to AI Tutor", icon: Brain },
    ],
  },
];
